#!/bin/sh
set -eu

: "${APP_MIGRATOR_DB_PASSWORD:?APP_MIGRATOR_DB_PASSWORD is required}"
: "${APP_RUNTIME_DB_PASSWORD:?APP_RUNTIME_DB_PASSWORD is required}"

psql --set=ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set=migrator_password="$APP_MIGRATOR_DB_PASSWORD" \
  --set=runtime_password="$APP_RUNTIME_DB_PASSWORD" <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_migrator') THEN
    CREATE ROLE app_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
    CREATE ROLE app_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;
ALTER ROLE app_migrator PASSWORD :'migrator_password';
ALTER ROLE app_runtime PASSWORD :'runtime_password';
REVOKE ALL ON DATABASE CURRENT_DATABASE() FROM PUBLIC;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE CURRENT_DATABASE() TO app_migrator;
GRANT CONNECT, TEMPORARY ON DATABASE CURRENT_DATABASE() TO app_runtime;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO app_migrator;
GRANT USAGE ON SCHEMA public TO app_runtime;
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app_migrator;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SQL
